"""Generates the two dnsmasq conf.d files NetworkManager's dnsmasq instance
reads: the always-on SafeSearch/HTTPS-RR-stripping config, and the sinkhole
(only armed in degraded mode).
"""
from __future__ import annotations

from dataclasses import dataclass, field

from dg_policy.hosts import normalize_host

HEADER = "# Generated by guardctl compile -- do not edit by hand.\n"


class DnsmasqRenderError(Exception):
    pass


@dataclass
class SafeSearchPin:
    hosts: list[str]  # one or more hostnames sharing this pinned address
    ipv4: str | None = None
    ipv6: str | None = None


@dataclass
class DnsmasqConfig:
    strip_ech: bool = True
    strip_http3: bool = True
    safe_search_pins: list[SafeSearchPin] = field(default_factory=list)
    sinkhole_domains: dict[str, str] = field(default_factory=dict)  # domain -> rule_id (comment only)


def render_always_on(cfg: DnsmasqConfig) -> str:
    lines = [HEADER]
    if cfg.strip_ech:
        lines.append("filter-rr=HTTPS,SVCB")
    lines.append("")
    for pin in cfg.safe_search_pins:
        for host in pin.hosts:
            h = normalize_host(host)
            if not h:
                raise DnsmasqRenderError(f"bad SafeSearch host: {host!r}")
            if pin.ipv4:
                lines.append(f"host-record={h},{pin.ipv4}")
            if pin.ipv6:
                lines.append(f"host-record={h},{pin.ipv6}")
            if not pin.ipv4 and not pin.ipv6:
                raise DnsmasqRenderError(f"SafeSearch pin for {h} has no resolved address")
    return "\n".join(lines) + "\n"


def render_sinkhole(cfg: DnsmasqConfig) -> str:
    lines = [HEADER, "# Armed only in degraded mode (watchdog renames this file's"]
    lines.append("# .off suffix on/off); harmless if present but unreferenced.")
    lines.append("")
    for domain, rule_id in sorted(cfg.sinkhole_domains.items()):
        d = normalize_host(domain)
        if not d:
            raise DnsmasqRenderError(f"bad sinkhole domain: {domain!r}")
        lines.append(f"address=/{d}/  # {rule_id}")
    return "\n".join(lines) + "\n"
